import type { DiscoveryCandidate } from "./discovery";
import { normalizeOpportunityUrl } from "./discovery";

/**
 * Public program pages only. Fields stay conservative: no invented deadlines,
 * employers, or eligibility beyond what the source program states on its site.
 */
const RAW_CATALOG: Array<Omit<DiscoveryCandidate, "canonicalUrl" | "alreadySaved">> = [
  {
    provider: "program_catalog",
    sourceUrl: "https://summerofcode.withgoogle.com/",
    title: "Google Summer of Code",
    organization: "Google Open Source",
    category: "internship",
    location: "Remote",
    remote: true,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["software", "ai_ml", "research"],
    skills: ["python", "open source"],
    excerpt:
      "Official Google Summer of Code program page. Mentored open-source internships for students and beginners. Confirm current eligibility and dates on the source site.",
    deadlineAt: null,
    quality: 86,
    requirements: [
      { id: "gsoc-student", text: "Student or beginner contributor eligible for Google Summer of Code", hard: true, kind: "education" },
      { id: "gsoc-oss", text: "Interest in open source software contribution", hard: false, kind: "experience" },
    ],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://www.outreachy.org/",
    title: "Outreachy Internships",
    organization: "Outreachy",
    category: "internship",
    location: "Remote",
    remote: true,
    educationLevel: "any",
    experienceLevel: "internship",
    domain: ["software", "ai_ml"],
    skills: ["python", "open source"],
    excerpt:
      "Official Outreachy internships page. Paid remote internships in open source and open science. Confirm round dates and eligibility on the source site.",
    deadlineAt: null,
    quality: 84,
    requirements: [
      { id: "out-remote", text: "Available for a remote internship", hard: true, kind: "availability" },
      { id: "out-underrep", text: "Program is intended for people underrepresented in tech", hard: false, kind: "eligibility" },
    ],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://fellowship.mlh.io/",
    title: "MLH Fellowship",
    organization: "Major League Hacking",
    category: "fellowship",
    location: "Remote",
    remote: true,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["software", "web"],
    skills: ["javascript", "python"],
    excerpt:
      "Official MLH Fellowship page. Remote software engineering fellowship. Confirm current tracks and requirements on the source site.",
    deadlineAt: null,
    quality: 78,
    requirements: [
      { id: "mlh-swe", text: "Software engineering or related student experience", hard: false, kind: "experience" },
    ],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://www.internshala.com/internships/internship-in-pakistan/",
    title: "Internshala internships in Pakistan",
    organization: "Internshala",
    category: "internship",
    location: "Pakistan",
    remote: false,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["software"],
    skills: [],
    excerpt:
      "Internshala listing index for internships in Pakistan. Individual postings must be opened on the source site; this card is the index, not a single employer.",
    deadlineAt: null,
    quality: 48,
    requirements: [{ id: "is-pk", text: "Located in or able to intern in Pakistan", hard: false, kind: "location" }],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://www.internshala.com/internships/work-from-home-internships/",
    title: "Internshala work-from-home internships",
    organization: "Internshala",
    category: "internship",
    location: "Remote",
    remote: true,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["software", "ai_ml"],
    skills: [],
    excerpt:
      "Internshala index of work-from-home internships. Confirm each employer posting on the source site before applying.",
    deadlineAt: null,
    quality: 48,
    requirements: [{ id: "is-remote", text: "Available for a remote internship", hard: false, kind: "availability" }],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://pk.linkedin.com/jobs/artificial-intelligence-intern-jobs",
    title: "LinkedIn: Artificial intelligence intern jobs in Pakistan",
    organization: "LinkedIn",
    category: "internship",
    location: "Pakistan",
    remote: false,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["ai_ml"],
    skills: ["python"],
    excerpt:
      "LinkedIn search results for AI intern roles in Pakistan. Listings change; open the source search to see current employers. Nothing here invents a specific company posting.",
    deadlineAt: null,
    quality: 42,
    requirements: [
      { id: "li-ai", text: "Interest or coursework in artificial intelligence or machine learning", hard: false, kind: "skills" },
    ],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://careers.google.com/jobs/results/?distance=50&q=machine%20learning%20intern",
    title: "Google Careers: machine learning intern search",
    organization: "Google",
    category: "internship",
    location: "Remote",
    remote: true,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["ai_ml", "software"],
    skills: ["python", "machine learning"],
    excerpt:
      "Official Google Careers search for machine learning intern roles. Open the source URL for live openings; do not treat this card as a guaranteed seat.",
    deadlineAt: null,
    quality: 80,
    requirements: [
      { id: "g-ml", text: "Machine learning or related coursework", hard: false, kind: "education" },
      { id: "g-py", text: "Skill: Python", hard: false, kind: "skills" },
    ],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://careers.microsoft.com/v2/global/en/search?q=internship%20machine%20learning",
    title: "Microsoft Careers: machine learning internship search",
    organization: "Microsoft",
    category: "internship",
    location: "Remote",
    remote: true,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["ai_ml", "software"],
    skills: ["python"],
    excerpt:
      "Official Microsoft Careers search for machine learning internships. Confirm locations and eligibility on the source site.",
    deadlineAt: null,
    quality: 80,
    requirements: [{ id: "ms-intern", text: "Currently enrolled student eligible for an internship", hard: false, kind: "education" }],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://www.daad.de/en/studying-in-germany/scholarships/",
    title: "DAAD scholarships",
    organization: "DAAD",
    category: "scholarship",
    location: "Germany",
    remote: false,
    educationLevel: "undergraduate",
    experienceLevel: "any",
    domain: ["research"],
    skills: [],
    excerpt:
      "Official DAAD scholarships overview. Individual awards have their own deadlines and rules on the source site.",
    deadlineAt: null,
    quality: 82,
    requirements: [{ id: "daad-enrolled", text: "University student eligible for DAAD funding", hard: false, kind: "education" }],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://www.kaggle.com/competitions",
    title: "Kaggle competitions",
    organization: "Kaggle",
    category: "hackathon",
    location: "Remote",
    remote: true,
    educationLevel: "any",
    experienceLevel: "any",
    domain: ["ai_ml", "data"],
    skills: ["python", "machine learning"],
    excerpt:
      "Official Kaggle competitions index. Each competition has its own rules and prizes. This is not an internship posting.",
    deadlineAt: null,
    quality: 70,
    requirements: [{ id: "kaggle-ml", text: "Skill: Python", hard: false, kind: "skills" }],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://huggingface.co/jobs",
    title: "Hugging Face jobs",
    organization: "Hugging Face",
    category: "job",
    location: "Remote",
    remote: true,
    educationLevel: "any",
    experienceLevel: "entry",
    domain: ["ai_ml"],
    skills: ["python", "pytorch"],
    excerpt:
      "Official Hugging Face jobs board. Open the source page for current roles; do not invent a specific opening from this card.",
    deadlineAt: null,
    quality: 76,
    requirements: [{ id: "hf-ml", text: "Skill: Python", hard: false, kind: "skills" }],
  },
  {
    provider: "program_catalog",
    sourceUrl: "https://careers.un.org/jobsearch",
    title: "UN Careers job search",
    organization: "United Nations",
    category: "internship",
    location: "Remote",
    remote: true,
    educationLevel: "undergraduate",
    experienceLevel: "internship",
    domain: ["policy", "research"],
    skills: [],
    excerpt:
      "Official UN Careers search. Internship and job listings must be confirmed on the source site.",
    deadlineAt: null,
    quality: 74,
    requirements: [{ id: "un-student", text: "Enrolled student or recent graduate as required by the specific UN posting", hard: false, kind: "education" }],
  },
];

export function sourcedDiscoveryCatalog(): DiscoveryCandidate[] {
  return RAW_CATALOG.map((item) => ({
    ...item,
    canonicalUrl: normalizeOpportunityUrl(item.sourceUrl),
    alreadySaved: false,
  }));
}
